# Generated by Django 5.0.6 on 2024-05-31 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horoskop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('znak', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('dnevni', models.TextField()),
                ('nedeljni', models.TextField()),
                ('mesecni', models.TextField()),
                ('godisnji', models.TextField()),
            ],
        ),
    ]
